/* 
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    /// CatAllOf
    /// </summary>
    public partial class CatAllOf : IEquatable<CatAllOf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CatAllOf" /> class.
        /// </summary>
        /// <param name="declawed">declawed.</param>
        public CatAllOf(bool? declawed = default)
        {
            Declawed = declawed;
        }

        /// <summary>
        /// Gets or Sets Declawed
        /// </summary>
        [JsonProperty("declawed", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Declawed { get; set; }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((CatAllOf)obj);
        }

        /// <summary>
        /// Returns true if CatAllOf instances are equal
        /// </summary>
        /// <param name="other">Instance of CatAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CatAllOf? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return 
                Declawed == other.Declawed;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            var hashCode = new HashCode();
            hashCode.Add(Declawed);
            return hashCode.ToHashCode();
        }
    }
}
