/* 
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    /// Just a string to inform instance is up and running. Make it nullable in hope to get it as pointer in generated model.
    /// </summary>
    public partial class HealthCheckResult : IEquatable<HealthCheckResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthCheckResult" /> class.
        /// </summary>
        /// <param name="nullableMessage">nullableMessage.</param>
        public HealthCheckResult(string? nullableMessage = default)
        {
            NullableMessage = nullableMessage;
        }

        /// <summary>
        /// Gets or Sets NullableMessage
        /// </summary>
        [JsonProperty("NullableMessage", NullValueHandling = NullValueHandling.Ignore)]
        public string? NullableMessage { get; set; }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((HealthCheckResult)obj);
        }

        /// <summary>
        /// Returns true if HealthCheckResult instances are equal
        /// </summary>
        /// <param name="other">Instance of HealthCheckResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HealthCheckResult? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return 
                NullableMessage == other.NullableMessage;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            var hashCode = new HashCode();
            hashCode.Add(NullableMessage);
            return hashCode.ToHashCode();
        }
    }
}
