/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    /// InlineResponseDefault
    /// </summary>
    public partial class InlineResponseDefault : IEquatable<InlineResponseDefault>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefault" /> class.
        /// </summary>
        /// <param name="_string">_string.</param>
        public InlineResponseDefault(Foo? _string = default)
        {
            String = _string;
        }

        /// <summary>
        /// Gets or Sets String
        /// </summary>
        [JsonProperty("string", NullValueHandling = NullValueHandling.Ignore)]
        public Foo? String { get; set; }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((InlineResponseDefault)obj);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefault to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return 
                Equals(String, other.String);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            var hashCode = new HashCode();
            hashCode.Add(String);
            return hashCode.ToHashCode();
        }
    }
}
