/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Xunit;

using Org.OpenAPITools.Api;
using Org.OpenAPITools.Models;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Category
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Category
        //private Category instance;

        public CategoryTests()
        {
            // TODO uncomment below to create an instance of Category
            //instance = new Category();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Category
        /// </summary>
        [Fact]
        public void CategoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Category
            //Assert.IsInstanceOfType<Category> (instance, "variable 'instance' is a Category");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }
}
