/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Xunit;

using Org.OpenAPITools.Api;
using Org.OpenAPITools.Models;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponseDefault
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponseDefaultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponseDefault
        //private InlineResponseDefault instance;

        public InlineResponseDefaultTests()
        {
            // TODO uncomment below to create an instance of InlineResponseDefault
            //instance = new InlineResponseDefault();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponseDefault
        /// </summary>
        [Fact]
        public void InlineResponseDefaultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponseDefault
            //Assert.IsInstanceOfType<InlineResponseDefault> (instance, "variable 'instance' is a InlineResponseDefault");
        }


        /// <summary>
        /// Test the property 'String'
        /// </summary>
        [Fact]
        public void StringTest()
        {
            // TODO unit test for the property 'String'
        }

    }
}
