/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Xunit;

using Org.OpenAPITools.Api;
using Org.OpenAPITools.Models;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SpecialModelName
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpecialModelNameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpecialModelName
        //private SpecialModelName instance;

        public SpecialModelNameTests()
        {
            // TODO uncomment below to create an instance of SpecialModelName
            //instance = new SpecialModelName();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpecialModelName
        /// </summary>
        [Fact]
        public void SpecialModelNameInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpecialModelName
            //Assert.IsInstanceOfType<SpecialModelName> (instance, "variable 'instance' is a SpecialModelName");
        }


        /// <summary>
        /// Test the property 'SpecialPropertyName'
        /// </summary>
        [Fact]
        public void SpecialPropertyNameTest()
        {
            // TODO unit test for the property 'SpecialPropertyName'
        }

    }
}
